- include_vars: "{{ ansible_os_family }}.yml"

- include_tasks: install.yml

- include_tasks: configure.yml

- include_tasks: create_networks.yml
  loop: "{{ libvirt_networks }}"
  loop_control:
    loop_var: network

- include_tasks: create_vms.yml
  loop: "{{ libvirt_vms }}"
  loop_control:
    loop_var: vm
  when: vm.state != "destroyed" and (libvirt_vms|length > 0) and autocreate_vms

- include_tasks: destroy_vms.yml
  with_items: "{{ libvirt_vms }}"
  when: item.state == "destroyed" and (libvirt_vms|length > 0)

- include_tasks: destroy_networks.yml
  with_items: "{{ libvirt_networks }}"
  when: item.state == "destroyed"

